# Supported type: Package, Class, Method
# Supported level: INFO, WARN, DANGER, DISATER, LASTDAY
[[rules]]
type = "PACKAGE"
level = "INFO"
message = "Network operate"
packages = ["java.net", "java.nio", "java.io"]

[[rules]]
type = "METHOD"
level = "DANGER"
message = "exec"
class = "java.lang.Runtime"
method = "exec"

[[rules]]
type = "CLASS"
level = "INFO"
message = "File operate"
classes = ["java.io.File", "java.nio.Path", "java.net.URL"]